name: Automation Test Execution 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Cucumber Features Execution
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setting up Node.js 20
      uses: actions/setup-node@v4
      with:
        always-auth: true
        node-version: '20.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Tests
      run: npm test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results  

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: '**/test-results/screenshots/**/*.png'

    - name: Generate Cucumber Report
      if: always()
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber.json"

  upload:
    if: always()
    needs: tests
    name: Upload test report to pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
          path: './test-results/reports/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
  
